/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Type-check Rex source against a domain interface (.rexd). */
export declare function check(source: string, domain: string): Array<NodeDiagnostic>

/** Compile Rex source code to REXC bytecode with full optimizations. */
export declare function compile(source: string): string

/** Compile Rex source to REXC bytecode using a domain interface (.rexd). */
export declare function compileWithDomain(source: string, domain: string): string

/** Encode a JS value (JSON types) to RX bytecode with deduplication. */
export declare function encode(value: unknown): string

export interface NodeDiagnostic {
  kind: string
  start: number
  end: number
  message: string
}
