[package]
name = "rex-core"
version = "0.1.0"
edition = "2024"

[dependencies]
logos.workspace = true
rowan.workspace = true

[dev-dependencies]
criterion.workspace = true
serde_json = { version = "1", features = ["preserve_order"] }

[[test]]
name = "spec"
harness = false

[[bench]]
name = "compiler"
harness = false
