/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Compile Rex source code to REXC bytecode with full optimizations. */
export declare function compile(source: string): string

/** Encode a JS value (JSON types) to RX bytecode with deduplication. */
export declare function encode(value: unknown): string
