// AUTOGENERATED FILE
// This file was generated from rex.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface RexActionDict<T> extends BaseActionDict<T> {
  space?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  Program?: (this: NonterminalNode, arg0: IterationNode) => T;
  Expr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AssignExpr_assign?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  AssignExpr_value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AssignExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ExistenceExpr_and?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  ExistenceExpr_or?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  ExistenceExpr_value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ExistenceExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  BitExpr_and?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  BitExpr_xor?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  BitExpr_or?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  BitExpr_value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  BitExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  CompareExpr_binary?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  CompareExpr_value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  CompareExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AddExpr_add?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AddExpr_sub?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AddExpr_value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AddExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MulExpr_mul?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MulExpr_div?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MulExpr_mod?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MulExpr_value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MulExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  UnaryExpr_neg?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  UnaryExpr_not?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  UnaryExpr_delete?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  UnaryExpr_value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  UnaryExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PostfixExpr_chain?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  PostfixExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PostfixTail_navStatic?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  PostfixTail_navDynamic?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  PostfixTail_call?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  PostfixTail?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ArgList?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_break?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_continue?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_true?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_false?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_null?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_undefined?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_self?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_identifier?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_group?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  PrimaryExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Place?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhenExpr?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: NonterminalNode, arg4: IterationNode, arg5: NonterminalNode) => T;
  UnlessExpr?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: NonterminalNode, arg4: IterationNode, arg5: NonterminalNode) => T;
  ElsePart_elseWhen?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  ElsePart_else?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  ElsePart?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ForExpr?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: NonterminalNode, arg4: NonterminalNode) => T;
  Block?: (this: NonterminalNode, arg0: IterationNode) => T;
  Array?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  ArrayBody_comprehension?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  ArrayBody_values?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ArrayBody?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Object?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  ObjectBody_comprehension?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode, arg4: NonterminalNode) => T;
  ObjectBody_pairs?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ObjectBody?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  IterBinding_keyValueIn?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: NonterminalNode, arg4: NonterminalNode) => T;
  IterBinding_valueIn?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  IterBinding_keyOf?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  IterBinding_implicit?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  IterBinding?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Pair?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  ObjKey_bare?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ObjKey_number?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ObjKey_string?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ObjKey_computed?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  ObjKey?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  KeyName?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  CompareOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  AssignOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Any?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode) => T;
  Identifier?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  nameHead?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  nameTail?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  Reserved?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  trueKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  falseKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  nullKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  undefinedKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  selfKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  whenKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  unlessKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  forKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  inKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  ofKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  doKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  elseKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  endKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  breakKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  continueKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  andKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  orKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  deleteKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  stringKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  numberKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  objectKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  arrayKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  booleanKw?: (this: NonterminalNode, arg0: TerminalNode) => T;
  String?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  DQuotedString?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  dStringChar?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  SQuotedString?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  sStringChar?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  escape?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  escapeChar?: (this: NonterminalNode, arg0: TerminalNode) => T;
  hexEscape?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  unicodeEscape?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: NonterminalNode, arg4: NonterminalNode) => T;
  hex?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  Number?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  hexNumber?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode, arg2: IterationNode) => T;
  binaryNumber?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode, arg2: IterationNode) => T;
  decimalNumber?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode, arg2: IterationNode, arg3: IterationNode, arg4: IterationNode) => T;
  decimalInteger_nonZero?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  decimalInteger_zero?: (this: NonterminalNode, arg0: TerminalNode) => T;
  decimalInteger?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  bit?: (this: NonterminalNode, arg0: TerminalNode) => T;
  exponent?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  nonZeroDigit?: (this: NonterminalNode, arg0: TerminalNode) => T;
  comment?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  lineComment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  blockComment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
}

export interface RexSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: RexActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: RexActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: RexActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: RexActionDict<T>): this;
}

export interface RexGrammar extends Grammar {
  createSemantics(): RexSemantics;
  extendSemantics(superSemantics: RexSemantics): RexSemantics;
}

declare const grammar: RexGrammar;
export default grammar;

