/** Color palette for REXC node kinds, matching the dark theme. */
export const KIND_COLORS: Record<string, string> = {
	string: '#ce9178',
	bareString: '#ce9178',
	number: '#b5cea8',
	integer: '#b5cea8',
	decimal: '#b5cea8',
	boolean: '#569cd6',
	null: '#569cd6',
	undefined: '#569cd6',
	object: '#dcdcaa',
	array: '#dcdcaa',
	call: '#dcdcaa',
	reference: '#c586c0',
	pointer: '#c586c0',
	pathChain: '#c586c0',
	variable: '#9cdcfe',
	self: '#9cdcfe',
	opcode: '#4ec9b0',
	when: '#c586c0',
	unless: '#c586c0',
	alt: '#c586c0',
	all: '#c586c0',
	forIn: '#c586c0',
	forOf: '#c586c0',
	while: '#c586c0',
	set: '#f48771',
	swap: '#f48771',
	delete: '#f48771',
	arrayComp: '#dcdcaa',
	objectComp: '#dcdcaa',
	loopControl: '#c586c0',
}

/** Short tag labels for type pills. */
export const KIND_TAGS: Record<string, string> = {
	object: 'OBJ',
	array: 'ARR',
	pointer: 'PTR',
	pathChain: 'CHAIN',
	call: 'CALL',
	when: 'WHEN',
	unless: 'UNLESS',
	alt: 'ALT',
	all: 'ALL',
	forIn: 'FORIN',
	forOf: 'FOROF',
	while: 'WHILE',
	set: 'SET',
	swap: 'SWAP',
	delete: 'DEL',
	arrayComp: 'ARRC',
	objectComp: 'OBJC',
}
